config/routes.rb
Store::Application.routes.draw do

  get '/items' => 'items#index'
  post 'line_items/:item_id' => 'line_items#create', as: :line_items
  get 'carts/:id' => 'carts#show', as: :cart
  delete '/carts/:id' => 'carts#destroy'
  get '/promotions' => 'promotions#index'

  root 'items#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_item(item_id)
    current_item = line_items.find_by(item_id: item_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(item_id: item_id)
    end

    current_item
  end

  def total
    total = 0.0

    line_items.each do |line_item|
      total += line_item.sub_total
    end

    total.round(2)
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :line_items
  belongs_to :promotion
  delegate :name, :kind, :quantity, :discount, to: :promotion, prefix: true

  before_destroy :ensure_not_referenced_by_any_line_item

  def ensure_not_referenced_by_any_line_item
    if line_items.any?
      errors.add(:base, "Item is present into line_item")
      return false
    else
      return true
    end
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart

  delegate :code, :name, :price, to: :item, prefix: true
  def sub_total
    (quantity * item.price).round(2)
  end
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include CurrentCart
  before_action :set_cart
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :calculate_total, only: [:show]

  expose(:cart)


  def calculate_total
    co = Checkout.new(Promotion.all)
    cart.line_items.each do |line_item|
      (1..line_item.quantity).each { co.scan(line_item.item) }
    end
    @total = co.total
  end

  def destroy
    if cart.destroy
      flash[:notice] = "Cart emptied successfully"
      redirect_to items_path
    end
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

private
  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  expose(:items)
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  def create
    item       = Item.find(params[:item_id])
    @line_item = @cart.add_item(item.id)

    if @line_item.save
      redirect_to cart_path(@line_item.cart), notice: "Product added to your cart"
    else
      render 'items/index'
    end
  end

protected
  def line_item_params
    params.require(:line_item).permit(:item_id)
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  expose(:promotions)
end

app/helpers/application_helper.rb
module ApplicationHelper
  def item_has_promotion?(item)
    return item.promotion_name if item.promotion && item.promotion.in?(Promotion.all)
  end

  def active?(a, b)
    return "active" if current_page?(controller: a, action: b)
    ""
  end
end

app/views/carts/show.html.erb
<h1>Cart:</h1>

<table class="table">
  <thead>
    <th>Code</th>
    <th>Name</th>
    <th>Price</th>
    <th>Count</th>
    <th>Promotion</th>
    <th>Subtotal</th>
  </thead>
  <tfoot>
    <tr>
      <td colspan="5"> <strong>Total</strong></td>
      <td> <strong><%= cart.total %></strong></td>
    </tr>
    <% if cart.total != @total %>
      <tr class="discount">
        <td colspan="5"><strong>Total with Discount</strong></td>
        <td> <strong><%= @total %></strong></td>
      </tr>
    <% end -%>
  </tfoot>
  <tbody>
    <% cart.line_items.each do |line_item| %>
      <tr>
        <td> <%= line_item.item_code %></td>
        <td> <%= line_item.item_name %></td>
        <td> <%= line_item.item_price %></td>
        <td> <%= line_item.quantity %></td>
        <td> <%= item_has_promotion?(line_item.item) %></td>
        <td> <%= line_item.sub_total %></td>
      </tr>
    <% end -%>
  </tbody>

</table>

<%= link_to items_path, class: 'btn btn-info' do %>
  <i class="icon-share-alt glyphw"></i>
  Continue shopping
<% end -%>

<%= link_to cart, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
  <i class="icon-trash glyphw"></i> Empty Cart
<% end -%>

app/views/items/index.html.erb
<h1> Products </h1>
<table class="table">
  <thead>
    <th>Code</th>
    <th>Name</th>
    <th>Price</th>
    <th>Promotions</th>
    <th>Action</th>
  </thead>

  <tbody>
    <% items.each do |item| %>
      <tr>
        <td> <%= item.code %></td>
        <td> <%= item.name %></td>
        <td> <%= item.price %></td>
        <td> <%= item_has_promotion?(item) %></td>
        <td>
          <%= link_to line_items_path(item), method: :post, class: "btn btn-success" do %>
            <i class="icon-shopping-cart glyphw" id="cart"></i>
            Add to cart
          <% end %>
        </td>
      </tr>
    <% end -%>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <meta name="viewport" content="width=device-width, ➥initial-scale=1.0">
  <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true%>
  <%= javascript_include_tag "application","data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <%= link_to 'Store online', root_path, class: "brand" %>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span3">
        <%= render 'shared/menu', cart: @cart %>
      </div>
      <div class="span9">
        <%= render 'shared/message' %>
        <%= yield %>
      </div>
    </div>
    <hr/>
    <footer></footer>
  </div>
</body>
</html>

app/views/promotions/index.html.erb
<h1>Promotions:</h1>

<table class="table">
  <thead>
    <th>Name</th>
    <th>Count</th>
    <th>Discount</th>
  </thead>
  <tfoot>
    <tr>
      <td colspan="3"> <strong>* Valid only for October and September of 2013</strong></td>
    </tr>
    </tfoot>
  <tbody>
    <% promotions.each do |promotion| %>
      <tr>
        <td> <%= promotion.name %></td>
        <td> <%= promotion.quantity %></td>
        <td> <%= promotion.discount %></td>
      </tr>
    <% end -%>
  </tbody>

</table>

<%= link_to "Go to Store", items_path %>

app/views/shared/_menu.html.erb
<ul class="nav nav-list">
  <li class="nav-header">Products</li>
  <li class="<%= active?('items', 'index') %>">
    <%= link_to items_path do %>
      <i class="icon-th-list"></i> All items
      <span class="badge badge-info"><%= Item.count %></span>
    <% end -%>
  </li>
  <% if cart.line_items.any? %>
    <li class="nav-header">My Cart</li>
    <li class="<%= 'active' if current_page?(cart_path(cart)) %>" >
      <%= link_to cart_path(cart) do %>
        <i class="icon-shopping-cart"></i> Show Cart
        <span class="badge badge-info"><%= cart.line_items.sum(:quantity) %></span>
      <% end -%>
    </li>
    <li class="">
      <%= link_to cart, method: :delete, confirm: 'Are you sure?' do %>
        <i class="icon-trash"></i>
        Empty cart
      <% end -%>
    </li>
  <% end -%>
  <li class="nav-header">Promotions</li>
  <li class="<%= active?('promotions', 'index') %>">
    <%= link_to promotions_path do %>
      <i class="icon-bullhorn"></i> All
      <span class="badge badge-info"><%= Promotion.count %></span>
    <% end -%>
  </li>
</ul>

app/views/shared/_message.html.erb
<% if flash[:alert] %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert" href="#">×</a><%= flash[:alert] %>
  </div>
<% end -%>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <a class="close" data-dismiss="alert" href="#">×</a><%= flash[:notice] %>
  </div>
<% end -%>